name: Staging

on:
  push:
    branches:
      - 'main'

jobs:
  Staging-CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2 
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'true'

      - name: setup jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Short SHA
        id: sha
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: build tag and push image to registry
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          PRODUCT: google-jib
          IMAGE_TAG: ${{ steps.sha.outputs.sha_short  }}
        run: |
          mvn compile com.google.cloud.tools:jib-maven-plugin:3.3.2:build \
          -Dimage=$REGISTRY/$PRODUCT:$IMAGE_TAG
        shell: bash

  Staging-CD:
    name: Staging-CD
    needs: [ Staging-CI ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Manifest repo
        uses: actions/checkout@v3
        with:
          repository: piaa10/google-jib-manifest.git
          token: ${{ secrets.GH_PAT }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2 
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Update Kubeconfig
        shell: bash
        run: |
          aws eks update-kubeconfig --name solvians-staging-pipeline --region eu-west-2

      - name: Configure kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.27.1'
        id: install

      - name: Apply Manifest
        shell: bash
        run: |
          kubectl apply -f my-manifests.yaml
